FROM rocker/r-base:4.2.3

RUN R -e "install.packages('argparse',dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('RNifti',dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN apt-get update && apt-get install -y --no-install-recommends build-essential r-base r-cran-randomforest python3.6 python3-pip python3-setuptools python3-dev
RUN R -e "install.packages('R.utils',dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('rmarchingcubes',dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('fields',dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('png',dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('Rvcg',dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('oce',dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('remotes',dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('s2dverification',dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('stringr',dependencies=TRUE, repos='http://cran.rstudio.com/')"
#RUN apt install libgl1-mesa-dev -y
#RUN apt install libglu1-mesa-dev -y
#RUN R -e "remotes::install_github('dmurdoch/rgl@v1.1.3')"
#RUN apt install xorg -y

COPY Nifti2Skifti.R .
COPY writeSkifti.R .
COPY writeCSV.R .
COPY Skifti_view.R .
RUN mkdir /enigmaDTI
COPY ./enigmaDTI/ENIGMA_DTI_FA_skeleton_mask.nii.gz /enigmaDTI
COPY Postprocess.R .
## run the script
ENTRYPOINT ["Rscript", "./Postprocess.R"]
